export default {
  COLORS: {
    MAIN: "#FFFFFF",
    PRIMARY: "#0F52BA",
    BLACK: "#000000",
    LIGHT_GRAY: "#EEEEEE",
    LIGHT_GRAY_SECONDARY: "#BFBFBF",
    DARK_GRAY: "#373737",
    GREEN_PRIMARY: "#B5F48A",
    GREEN_SECONDARY: "#356B10",
    ERROR_PRIMARY: "#BA1A1A",
    ERROR_SECONDARY: "#FFDAD6",
  },
};
